# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-app-for4"
client_id = "213816cd7ce439ee14fb58a9e7fd66c3"
application_url = "https://render-app-test1127.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://render-app-test1127.onrender.com/auth/callback",
  "https://render-app-test1127.onrender.com/auth/shopify/callback",
  "https://render-app-test1127.onrender.com/api/auth/callback",
  "https://render-app-test1127.onrender.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-si-matsubara.myshopify.com"
